const names = [
    `Doctor`,
    `Autumn`,
    `Daria`,
    `Janitor`,
    `Princess`,
    `Crumbles`,
    `Amore`,
    `Dud`,
    `Tank`,
    `Dearest`,
    `Short`,
    `Conductor`,
    `Coach`,
    `Braveheart`,
    `Boomer`,
    `Muffin`,
    `Half`,
    `Buttercup`,
    `Doll`,
    `Duckling`,
    `Pork`,
    `Boomhauer`,
    `Smudge`,
    `Hulk`,
    `Pinkie`,
    `Beef`,
    `Tater`,
    `Piglet`,
    `Rockette`,
    `Fig`,
    `Kid`,
    `Azkaban`,
    `Thor`,
    `Chickie`,
    `Chubs`,
    `Chain`,
    `Tootsie`,
    `Bruiser`,
    `Monkey`,
    `Smarty`,
    `Grease`,
    `Pookie`,
    `Fellow`,
    `Sassy`,
    `Psycho`,
    `Ami`,
    `Bacon`,
    `Dimples`,
    `Frogger`,
    `Knuckles`,
    `Wifey`,
    `Brutus`,
    `Thunder`,
    `Dinosaur`,
    `Diesel`,
    `Cheesestick`,
    `Creep`,
    `Cat`,
    `Lion`,
    `Sunny`,
    `Chance`,
    `Cheerio`,
    `Munchkin`,
    `Buckeye`,
    `Skinny`,
    `Mama`,
    `Blondie`,
    `Congeniality`,
    `Cutie`,
    `Pearl`,
    `Slick`,
    `Cotton`,
    `Mustache`,
    `Amorcita`,
    `Bellbottoms`,
    `Dimpling`,
    `Creedence`,
    `Twinkie`,
    `Queen`,
    `Shuttershy`,
    `Foxy`,
    `Itchy`,
    `Bumpkin`,
    `Bubblegum`,
    `Diet`,
    `Fly`,
    `Hawk`,
    `Champ`,
    `Pickle`,
    `Rocketfuel`,
    `Biscuit`,
    `Rabbit`,
    `Gingersnap`,
    `Baby`,
    `Candycane`,
    `Piggy`,
    `Twig`,
    `Pig`,
    `Cherry`,
    `Dirty`
]

module.exports = {
    generateUsername: (req, res) => {
        const name1 = Math.floor(Math.random()*names.length);
        const name2 = Math.floor(Math.random()*names.length);
        const number = Math.floor(Math.random()*100);

        const username = `${names[name1]}${names[name2]}${number}`;

        res.json({name: username});
    }
}