import express from 'express';

const names: string[] = [
    `Doctor`,
    `Autumn`,
    `Daria`,
    `Janitor`,
    `Princess`,
    `Crumbles`,
    `Amore`,
    `Tank`,
    `Dearest`,
    `Short`,
    `Conductor`,
    `Coach`,
    `Braveheart`,
    `Muffin`,
    `Half`,
    `Buttercup`,
    `Doll`,
    `Duckling`,
    `Pork`,
    `Smudge`,
    `Hulk`,
    `Pinkie`,
    `Beef`,
    `Tater`,
    `Piglet`,
    `Rockette`,
    `Fig`,
    `Kid`,
    `Chickie`,
    `Chubs`,
    `Chain`,
    `Tootsie`,
    `Bruiser`,
    `Monkey`,
    `Smarty`,
    `Grease`,
    `Pookie`,
    `Fellow`,
    `Ami`,
    `Bacon`,
    `Dimples`,
    `Frogger`,
    `Knuckles`,
    `Wifey`,
    `Brutus`,
    `Thunder`,
    `Dinosaur`,
    `Diesel`,
    `Cheesestick`,
    `Cat`,
    `Lion`,
    `Sunny`,
    `Chance`,
    `Cheerio`,
    `Munchkin`,
    `Buckeye`,
    `Pearl`,
    `Slick`,
    `Cotton`,
    `Mustache`,
    `Amorcita`,
    `Bellbottoms`,
    `Creedence`,
    `Twinkie`,
    `Queen`,
    `Shuttershy`,
    `Itchy`,
    `Bubblegum`,
    `Diet`,
    `Fly`,
    `Hawk`,
    `Champ`,
    `Pickle`,
    `Rocketfuel`,
    `Biscuit`,
    `Rabbit`,
    `Gingersnap`,
    `Baby`,
    `Candycane`,
    `Piggy`,
    `Twig`,
    `Cherry`
]

module.exports.generateUsername = (req: express.Request, res: express.Response) => {
    const name1: number = Math.floor(Math.random()*names.length);
    const name2: number = Math.floor(Math.random()*names.length);
    const number: number = Math.floor(Math.random()*100);

    const username: string = `${names[name1]}${names[name2]}${number}`;

    res.json({name: username});
}